### ISSUE TITLE
[Feature Request] Site prompt

### ISSUE THREAD

**Issue by hunkim** [hunkimForks/chatgpt-arxiv-extension#1]
Now we can modify the default prompt.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/901975/217971902-855e4c2f-b4cd-44d5-ae21-89a6a95a05c5.png">

I want to be able to set the prompt for each site.

For example, "arxiv":"prompt for arxiv" 

In the panel, on the left side, we can define site name: 'default', 'new" and save prompt.

**Comment by hunkim** [comment]
@pungrue26 Do you think you can take a look?

**Comment by joonhok-fittube** [comment]
@hunkim Let me take this. @pungrue26 is my personal account but I found I lost my access to that account. :(

**Comment by joonhok-fittube** [comment]
Okay, I finished getting myself familiarize with the chrome extension development and understanding the requirement of this issue.

There are a couple of ways to design the new feature. 

1) Listing each pair as a row in a table, like Chrome displays saved passwords. Because it's a row in a table, each prompt will be displayed in a single line input field.
<img width="1440" alt="Screen Shot 2023-02-10 at 10 50 14 AM" src="https://user-images.githubusercontent.com/85531927/217996243-7c2b0ed4-a08e-4f1b-8403-5430d0000eed.png">

2) Listing each pair as a card, displaying the full prompt for each site.

I think it makes more sense to pursue the second option with the following assumptions.

- Most users will not need more than 5 pairs.
- Prompts are usually 3-5 lines long, and very important information for the user.

Let me know if you have any feedback on this. I will proceed with the second option first.

**Comment by joonhok-fittube** [comment]
@hunkim Finished the work and created a PR. Please have a look.

**Comment by hunkim** [comment]
@joonhok-fittube good job!
